In [1]:
%pip install pykrx pymysql mysql-connector-python sqlalchemy

Requirement already satisfied: pykrx in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (1.0.48)
Requirement already satisfied: pymysql in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (1.1.1)
Requirement already satisfied: mysql-connector-python in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (9.0.0)
Requirement already satisfied: sqlalchemy in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (2.0.35)
Requirement already satisfied: requests in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from pykrx) (2.32.3)
Requirement already satisfied: pandas in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from pykrx) (2.2.2)
Requirement already satisfied: datetime in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from pykrx) (5.5)
Requirement already satisfied: numpy in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from pykrx) (2.0.0)
Requirement already satisfied: xlrd in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from pykrx) (2.0.1)
Requirement already satisfied: deprecated in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from pykrx) (1.2.14)
Requirement already satisfied: multipledispatch in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from pykrx) (1.0.0)
Requirement already satisfied: matplotlib in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from pykrx) (3.9.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: zope.interface in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from datetime->pykrx) (7.0.3)
Requirement already satisfied: pytz in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from datetime->pykrx) (2024.1)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from deprecated->pykrx) (1.16.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from matplotlib->pykrx) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from matplotlib->pykrx) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from matplotlib->pykrx) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from matplotlib->pykrx) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from matplotlib->pykrx) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from matplotlib->pykrx) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from matplotlib->pykrx) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from matplotlib->pykrx) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from pandas->pykrx) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from requests->pykrx) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from requests->pykrx) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from requests->pykrx) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from requests->pykrx) (2024.7.4)
Requirement already satisfied: six>=1.5 in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from python-dateutil>=2.7->matplotlib->pykrx) (1.16.0)
Requirement already satisfied: setuptools in c:\users\student\documents\kb-final-project\rag\stock-info\lib\site-packages (from zope.interface->datetime->pykrx) (75.1.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from pykrx import stock
stock.get_previous_business_days(year=2024, month=10)

[Timestamp('2024-10-02 00:00:00'),
 Timestamp('2024-10-04 00:00:00'),
 Timestamp('2024-10-07 00:00:00'),
 Timestamp('2024-10-08 00:00:00'),
 Timestamp('2024-10-10 00:00:00'),
 Timestamp('2024-10-11 00:00:00'),
 Timestamp('2024-10-14 00:00:00'),
 Timestamp('2024-10-15 00:00:00'),
 Timestamp('2024-10-16 00:00:00'),
 Timestamp('2024-10-17 00:00:00'),
 Timestamp('2024-10-18 00:00:00'),
 Timestamp('2024-10-21 00:00:00'),
 Timestamp('2024-10-22 00:00:00')]

In [3]:
import os
from dotenv import load_dotenv
from pykrx import stock
from pykrx import bond

load_dotenv()

KIS_APP_KEY = os.getenv("KIS_APP_KEY")
KIS_APP_SECRET = os.getenv("KIS_APP_SECRET")
KIS_ACC_NO = os.getenv("KIS_ACC_NO")
DB_HOST = os.getenv("DB_HOST")
DB_USERNAME = os.getenv("DB_USERNAME")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_SCHEME = os.getenv("DB_SCHEME")
DB_PORT = os.getenv("DB_PORT")

In [4]:
import pandas as pd
import requests as rq
from sqlalchemy import create_engine
from io import StringIO


def get_krx_otp(otp_params, headers):
  krx_gen_otp_url = 'http://data.krx.co.kr/comm/fileDn/GenerateOTP/generate.cmd'
  krx_otp = rq.post(krx_gen_otp_url, otp_params, headers = headers).text
  return krx_otp

def download_krx_index(at_date, market = None):
  if not market:
    kospi_df = download_krx_index(at_date, 'KOSPI')
    kosdaq_df = download_krx_index(at_date, 'KOSDAQ')
    return pd.concat([kospi_df, kosdaq_df])

  headers = {             
    "User-Agent": "Mozilla/5.0",
    "Referer": "http://data.krx.co.kr/"
  }
  otp_params = {
      'locale': 'ko_KR',
      'trdDd': at_date,
      'money': '1',
      'csvxls_isNo': 'false',
      'name': 'fileDown',
      'url': 'dbms/MDC/STAT/standard/MDCSTAT03501'
  }
  if market == 'KOSPI':
    otp_params |= { 'mktId': 'STK' }
  elif market == 'KOSDAQ':
    otp_params |= { 'mktId': 'KSQ', 'segTpCd': 'ALL' }

  otp = get_krx_otp(otp_params, headers)

  download_url = 'http://data.krx.co.kr/comm/fileDn/download_csv/download.cmd'
  download_params = {
      'code': otp
  }
  res = rq.post(download_url, download_params, headers = headers)
  res.encoding = 'euc-kr'
  return pd.read_csv(StringIO(res.text))



def download_krx_sector(at_date, market = None):
  if not market:
    kospi_df = download_krx_sector(at_date, 'KOSPI')
    kosdaq_df = download_krx_sector(at_date, 'KOSDAQ')
    return pd.concat([kospi_df, kosdaq_df])

  headers = {             
    "User-Agent": "Mozilla/5.0",
    "Referer": "http://data.krx.co.kr/"
  }
  otp_params = {
      'locale': 'ko_KR',
      'trdDd': at_date,
      'money': '1',
      'csvxls_isNo': 'false',
      'name': 'fileDown',
      'url': 'dbms/MDC/STAT/standard/MDCSTAT01901'
  }
  if market == 'KOSPI':
    otp_params |= { 'mktId': 'STK' }
  elif market == 'KOSDAQ':
    otp_params |= { 'mktId': 'KSQ', 'segTpCd': 'ALL' }

  otp = get_krx_otp(otp_params, headers)

  download_url = 'http://data.krx.co.kr/comm/fileDn/download_csv/download.cmd'
  download_params = {
      'code': otp
  }
  res = rq.post(download_url, download_params, headers = headers)
  res.encoding = 'euc-kr'
  return pd.read_csv(StringIO(res.text))


def download_stock_category(at_date, market = None):
  if not market:
    kospi_df = download_stock_category(at_date, 'KOSPI')
    kosdaq_df = download_stock_category(at_date, 'KOSDAQ')
    return pd.concat([kospi_df, kosdaq_df])

  headers = {             
    "User-Agent": "Mozilla/5.0",
    "Referer": "http://data.krx.co.kr/"
  }
  otp_params = {
      'locale': 'ko_KR',
      'trdDd': at_date,
      'money': '1',
      'csvxls_isNo': 'false',
      'name': 'fileDown',
      'url': 'dbms/MDC/STAT/standard/MDCSTAT03901'
  }
  if market == 'KOSPI':
    otp_params |= { 'mktId': 'STK' }
  elif market == 'KOSDAQ':
    otp_params |= { 'mktId': 'KSQ', 'segTpCd': 'ALL' }

  otp = get_krx_otp(otp_params, headers)

  download_url = 'http://data.krx.co.kr/comm/fileDn/download_csv/download.cmd'
  download_params = {
      'code': otp
  }
  res = rq.post(download_url, download_params, headers = headers)
  res.encoding = 'euc-kr'
  return pd.read_csv(StringIO(res.text))

def fetchSubCategory():
  engine = create_engine(f'mysql+pymysql://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_SCHEME}')

  query = "SELECT SUB_CATEGORY_ID, SUB_CATEGORY_NAME FROM SUB_CATEGORY"
  news_data = pd.read_sql(query, engine)

  return news_data

def fetchMainCategory():
  engine = create_engine(f'mysql+pymysql://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_SCHEME}')

  query = "SELECT MAIN_CATEGORY_ID, MAIN_CATEGORY_NAME FROM MAIN_CATEGORY"
  news_data = pd.read_sql(query, engine)

  return news_data

In [5]:
import datetime

# 현재 날짜를 YYYYMMDD 형식으로 변환
now = datetime.datetime.now()
# current_date_str = now.strftime('%Y%m%d')
current_date_str='20241010'

In [6]:
df_info = download_krx_sector(current_date_str)

In [7]:

df_index = download_krx_index(current_date_str)

In [8]:
sub_category_data = fetchSubCategory()

main_category_data = fetchMainCategory()

In [9]:
stock_category_data = download_stock_category(current_date_str)

In [10]:
stock_category_data = stock_category_data[['종목코드', '업종명']]

In [11]:
stock_category_data.rename(columns={'종목코드':'SHORT_CODE','업종명':'SUB_CATEGORY_NAME'}, inplace=True)

In [12]:
stock_category_data

     SHORT_CODE SUB_CATEGORY_NAME
0        095570              서비스업
1        006840              기타금융
2        027410              기타금융
3        282330               유통업
4        138930              기타금융
...         ...               ...
1749     024060                유통
1750     010240             기계·장비
1751     189980            음식료·담배
1752     037440             기타서비스
1753     238490             기계·장비

[2712 rows x 2 columns]

In [13]:
sub_category_data

    SUB_CATEGORY_ID SUB_CATEGORY_NAME
0                 1             숙박·음식
1                 2            음식료·담배
2                 3              음식료품
3                 4          전기·가스·수도
4                 5             전기가스업
5                 6               건설업
6                 7                건설
7                 8                은행
8                 9                증권
9                10                보험
10               11              기타금융
11               12                금융
12               13               통신업
13               14              전기전자
14               15            일반전기전자
15               16                운송
16               17             운수창고업
17               18           운송장비·부품
18               19                유통
19               20               유통업
20               21       농업, 임업 및 어업
21               22             비금속광물
22               23              철강금속
23               24              의료정밀
24               25               의약품
25               26                제약
26               27           의료·정밀기기
27               28             기타제조업
28               29                기계
29               30             기계·장비
30               31                화학
31               32             섬유·의류
32               33              섬유의복
33               34                금속
34               35               비금속
35               36              기타제조
36               37              운수장비
37               38             종이·목재
38               39              종이목재
39               40             오락·문화
40               41              서비스업
41               42             기타서비스
42               43           출판·매체복제

In [14]:
merged_stock_category = pd.merge(stock_category_data, sub_category_data, on='SUB_CATEGORY_NAME', how='inner')

In [15]:
merged_stock_category

     SHORT_CODE SUB_CATEGORY_NAME  SUB_CATEGORY_ID
0        095570              서비스업               41
1        006840              기타금융               11
2        027410              기타금융               11
3        282330               유통업               20
4        138930              기타금융               11
...         ...               ...              ...
2707     024060                유통               19
2708     010240             기계·장비               30
2709     189980            음식료·담배                2
2710     037440             기타서비스               42
2711     238490             기계·장비               30

[2712 rows x 3 columns]

In [16]:
df_info

,표준코드,단축코드,한글 종목명,한글 종목약명,영문 종목명,상장일,시장구분,증권구분,소속부,주식종류,액면가,상장주식수
0,KR7095570008,095570,AJ네트웍스보통주,AJ네트웍스,"AJ Networks Co.,Ltd.",2015/08/21,KOSPI,주권,NaN,보통주,1000,45252759
1,KR7006840003,006840,AK홀딩스보통주,AK홀딩스,"AK Holdings, Inc.",1999/08/11,KOSPI,주권,NaN,보통주,5000,13247561
2,KR7282330000,282330,BGF리테일보통주,BGF리테일,BGF Retail,2017/12/08,KOSPI,주권,NaN,보통주,1000,17283906
3,KR7027410000,027410,BGF보통주,BGF,BGF,2014/05/19,KOSPI,주권,NaN,보통주,1000,95716791
4,KR7138930003,138930,BNK금융지주보통주,BNK금융지주,BNK Financial Group Inc.,2011/03/30,KOSPI,주권,NaN,보통주,5000,320436727
...,...,...,...,...,...,...,...,...,...,...,...,...
1753,KR7024060006,024060,흥구석유,흥구석유,HeunguOil,1994/12/07,KOSDAQ,주권,중견기업부,보통주,100,15000000
1754,KR7010240000,010240,흥국,흥국,"HEUNGKUK METALTECH CO.,LTD.",2009/05/12,KOSDAQ,주권,우량기업부,보통주,500,12322696
1755,KR7189980006,189980,흥국에프엔비,흥국에프엔비,"HYUNGKUK F&B Co., Ltd",2015/08/07,KOSDAQ,주권,우량기업부,보통주,100,40137827
1756,KR7037440005,037440,희림종합건축사사무소,희림,Heerim Architects & Planners,2000/02/03,KOSDAQ,주권,우량기업부,보통주,500,13922475
1757,KR7238490007,238490,힘스,힘스,"HIMS CO., LTD.",2017/07/20,KOSDAQ,주권,벤처기업부,보통주,500,11312236

In [17]:
df_index

,종목코드,종목명,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
0,095570,AJ네트웍스,4735,5,0.11,367.0,12.90,778.0,6.08,9326.0,0.51,270,5.70
1,006840,AK홀딩스,13290,170,1.30,2635.0,5.04,NaN,NaN,44339.0,0.30,200,1.50
2,027410,BGF,3590,40,1.13,813.0,4.42,656.0,5.47,17286.0,0.21,120,3.34
3,282330,BGF리테일,111000,2700,2.49,11337.0,9.79,11845.0,9.37,62197.0,1.78,4100,3.69
4,138930,BNK금융지주,9220,50,0.55,1905.0,4.84,2645.0,3.49,31746.0,0.29,510,5.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1729,024060,흥구석유,20250,-1350,-6.25,78.0,259.62,NaN,NaN,5440.0,3.72,50,0.25
1730,010240,흥국,5000,80,1.63,1182.0,4.23,NaN,NaN,8598.0,0.58,240,4.80
1731,189980,흥국에프엔비,1850,-34,-1.80,221.0,8.37,224.0,8.27,2449.0,0.76,40,2.16
1732,037440,희림,5240,90,1.75,489.0,10.72,NaN,NaN,5583.0,0.94,150,2.86
1733,238490,힘스,4540,-230,-4.82,511.0,8.88,NaN,NaN,6174.0,0.74,50,1.10

In [18]:
df_info_mapping = {
    '단축코드': 'SHORT_CODE',
}

df_index_mapping = {
    '종목코드': 'SHORT_CODE',
}

# 컬럼명 매핑 적용
df_info.rename(columns=df_info_mapping, inplace=True)
df_index.rename(columns=df_index_mapping, inplace=True)

In [19]:
df_info_index = pd.merge(df_info, df_index, on='SHORT_CODE', how='outer')
df_info_index_stock_category = pd.merge(df_info_index, merged_stock_category, on="SHORT_CODE", how='inner')

In [20]:
df_info_index_stock_category

,표준코드,SHORT_CODE,한글 종목명,한글 종목약명,영문 종목명,상장일,시장구분,증권구분,소속부,주식종류,...,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률,SUB_CATEGORY_NAME,SUB_CATEGORY_ID
0,KR7000020008,000020,동화약품보통주,동화약품,DongwhaPharm,1976/03/24,KOSPI,주권,NaN,보통주,...,991.0,7.78,NaN,NaN,13413.0,0.57,180.0,2.33,의약품,25
1,KR7000040006,000040,KR모터스보통주,KR모터스,KR MOTORS,1976/05/25,KOSPI,주권,NaN,보통주,...,NaN,NaN,NaN,NaN,618.0,0.86,0.0,0.00,운수장비,37
2,KR7000050005,000050,경방보통주,경방,Kyungbang,1956/03/03,KOSPI,주권,NaN,보통주,...,NaN,NaN,NaN,NaN,29623.0,0.21,125.0,2.04,유통업,20
3,KR7000070003,000070,삼양홀딩스보통주,삼양홀딩스,SAMYANGHOLDINGS,1968/12/27,KOSPI,주권,NaN,보통주,...,22269.0,3.57,NaN,NaN,257475.0,0.31,3500.0,4.40,기타금융,11
4,KR7000071001,000075,삼양홀딩스1우선주,삼양홀딩스우,SAMYANGHOLDINGS(1P),1992/02/21,KOSPI,주권,NaN,구형우선주,...,NaN,NaN,NaN,NaN,NaN,NaN,3550.0,6.21,기타금융,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2707,KR8392080006,950170,제이티씨,JTC,JTC Inc.,2018/04/06,KOSDAQ,주식예탁증권,외국기업(소속부없음),보통주,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,유통,19
2708,KR8344390008,950190,고스트스튜디오,고스트스튜디오,GHOST STUDIO,2020/08/18,KOSDAQ,주식예탁증권,외국기업(소속부없음),보통주,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,출판·매체복제,43
2709,KR8840150005,950200,소마젠,소마젠,"Psomagen, Inc.",2020/07/13,KOSDAQ,주식예탁증권,외국기업(소속부없음),보통주,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,기타서비스,42
2710,KR8702070002,950210,프레스티지바이오파마KDR,프레스티지바이오파마,PRESTIGE BIOPHARMA LIMITED KDR,2021/02/05,KOSPI,주식예탁증권,NaN,보통주,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,서비스업,41
2711,KR8840140006,950220,네오이뮨텍,네오이뮨텍,"NeoImmuneTech, Inc.",2021/03/16,KOSDAQ,주식예탁증권,외국기업(소속부없음),보통주,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,기타서비스,42

In [21]:
merged_df_column_mapping = {
    '단축코드': 'SHORT_CODE',
    # '서브카테고리' : 'SUB_CATEGORY_ID',
    '한글 종목약명': 'STOCK_NAME',
    '표준코드': 'STANDARD_CODE',
    '시장구분': 'STOCK_EXCHANGE_MARKET',
    '상장주식수': 'MARKET_CAPITALIZATION',
    '시가': 'OPEN_PRICE',
    '종가': 'CLOSED_PRICE',
    '고가': 'HIGH_PRICE',
    '저가': 'LOW_PRICE',
    '거래정지': 'STOCK_TRADE_STATUS',
}


df_info_index_stock_category.rename(columns=merged_df_column_mapping, inplace=True)

In [22]:

real_index = [
 'SHORT_CODE',
 'STOCK_NAME',
 'SUB_CATEGORY_ID',
 'STANDARD_CODE',
 'STOCK_EXCHANGE_MARKET',
 'MARKET_CAPITALIZATION',
 'EPS',
 'PER',
 'BPS',
 'PBR',
]

df_info_index_stock_category = df_info_index_stock_category[real_index]

In [23]:
df_info_index_stock_category

,SHORT_CODE,STOCK_NAME,SUB_CATEGORY_ID,STANDARD_CODE,STOCK_EXCHANGE_MARKET,MARKET_CAPITALIZATION,EPS,PER,BPS,PBR
0,000020,동화약품,25,KR7000020008,KOSPI,27931470.0,991.0,7.78,13413.0,0.57
1,000040,KR모터스,37,KR7000040006,KOSPI,60132868.0,NaN,NaN,618.0,0.86
2,000050,경방,20,KR7000050005,KOSPI,27415270.0,NaN,NaN,29623.0,0.21
3,000070,삼양홀딩스,11,KR7000070003,KOSPI,8564271.0,22269.0,3.57,257475.0,0.31
4,000075,삼양홀딩스우,11,KR7000071001,KOSPI,304058.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2707,950170,JTC,19,KR8392080006,KOSDAQ,51746348.0,NaN,NaN,NaN,NaN
2708,950190,고스트스튜디오,43,KR8344390008,KOSDAQ,13579892.0,NaN,NaN,NaN,NaN
2709,950200,소마젠,42,KR8840150005,KOSDAQ,19236053.0,NaN,NaN,NaN,NaN
2710,950210,프레스티지바이오파마,41,KR8702070002,KOSPI,60096155.0,NaN,NaN,NaN,NaN
2711,950220,네오이뮨텍,42,KR8840140006,KOSDAQ,98867465.0,NaN,NaN,NaN,NaN

In [24]:
# 해당 데이터가 확보 안된 경우 사용
for column in [
 'STOCK_TRADE_STATUS']:
    if column not in df_info_index_stock_category.columns:
        df_info_index_stock_category[column] = 'A'

C:\Users\student\AppData\Local\Temp\ipykernel_22592\3712582700.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info_index_stock_category[column] = 'A'

In [25]:
df_info_index_stock_category['STOCK_EXCHANGE_MARKET'] = df_info_index_stock_category['STOCK_EXCHANGE_MARKET'].map({'KOSPI': "0", 'KOSDAQ': "1"})

C:\Users\student\AppData\Local\Temp\ipykernel_22592\3165155587.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info_index_stock_category['STOCK_EXCHANGE_MARKET'] = df_info_index_stock_category['STOCK_EXCHANGE_MARKET'].map({'KOSPI': "0", 'KOSDAQ': "1"})

In [26]:
df_info_index_stock_category

,SHORT_CODE,STOCK_NAME,SUB_CATEGORY_ID,STANDARD_CODE,STOCK_EXCHANGE_MARKET,MARKET_CAPITALIZATION,EPS,PER,BPS,PBR,STOCK_TRADE_STATUS
0,000020,동화약품,25,KR7000020008,0,27931470.0,991.0,7.78,13413.0,0.57,A
1,000040,KR모터스,37,KR7000040006,0,60132868.0,NaN,NaN,618.0,0.86,A
2,000050,경방,20,KR7000050005,0,27415270.0,NaN,NaN,29623.0,0.21,A
3,000070,삼양홀딩스,11,KR7000070003,0,8564271.0,22269.0,3.57,257475.0,0.31,A
4,000075,삼양홀딩스우,11,KR7000071001,0,304058.0,NaN,NaN,NaN,NaN,A
...,...,...,...,...,...,...,...,...,...,...,...
2707,950170,JTC,19,KR8392080006,1,51746348.0,NaN,NaN,NaN,NaN,A
2708,950190,고스트스튜디오,43,KR8344390008,1,13579892.0,NaN,NaN,NaN,NaN,A
2709,950200,소마젠,42,KR8840150005,1,19236053.0,NaN,NaN,NaN,NaN,A
2710,950210,프레스티지바이오파마,41,KR8702070002,0,60096155.0,NaN,NaN,NaN,NaN,A
2711,950220,네오이뮨텍,42,KR8840140006,1,98867465.0,NaN,NaN,NaN,NaN,A

In [27]:
from sqlalchemy import create_engine
from sqlalchemy import text
# MySQL 데이터베이스 연결 설정
# db_username = DB_USERNAME
# db_password = DB_PASSWORD
# db_host = DB_HOST
# db_name = DB_SCHEME
# db_port = DB_PORT

# SQLAlchemy 엔진 생성
engine = create_engine(f'mysql+pymysql://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_SCHEME}')

df_info_index_stock_category.to_sql(name='TEMP_STOCK', con=engine, if_exists='replace', index=False)

# 업데이트 쿼리 작성
update_query = """
INSERT INTO STOCK (SHORT_CODE, SUB_CATEGORY_ID, STOCK_NAME, STANDARD_CODE, STOCK_EXCHANGE_MARKET, 
                   EPS, PER, BPS, PBR, MARKET_CAPITALIZATION, STOCK_TRADE_STATUS, UPDATED_AT)
SELECT SHORT_CODE, SUB_CATEGORY_ID, STOCK_NAME, STANDARD_CODE, STOCK_EXCHANGE_MARKET, 
       EPS, PER, BPS, PBR, MARKET_CAPITALIZATION, STOCK_TRADE_STATUS, NOW()
FROM TEMP_STOCK
ON DUPLICATE KEY UPDATE 
    SUB_CATEGORY_ID = VALUES(SUB_CATEGORY_ID),
    STOCK_NAME = VALUES(STOCK_NAME),
    STANDARD_CODE = VALUES(STANDARD_CODE),
    STOCK_EXCHANGE_MARKET = VALUES(STOCK_EXCHANGE_MARKET),
    EPS = VALUES(EPS),
    PER = VALUES(PER),
    BPS = VALUES(BPS),
    PBR = VALUES(PBR),
    MARKET_CAPITALIZATION = VALUES(MARKET_CAPITALIZATION),
    STOCK_TRADE_STATUS = VALUES(STOCK_TRADE_STATUS),
    UPDATED_AT = NOW();
"""

# SQL 쿼리 실행
with engine.connect() as connection:
    connection.execute(text(update_query))

# # 임시 테이블 삭제
with engine.connect() as connection:
    connection.execute(text("DROP TABLE TEMP_STOCK"))

InvalidRequestError: Could not reflect: requested table(s) not available in Engine(mysql+pymysql://root:***@localhost:3306/PLEASE_GIVE_ME_ASSETS): (TEMP_STOCK)

In [49]:
data['업종명']

NameError: name 'data' is not defined

In [ ]:
count_df = data.groupby(by = '업종명').size().reset_index(name = 'Count').sort_values(by = 'Count').set_index('업종명')

for sector in count_df.index:
    print(sector)